### ISSUE TITLE
Probleme ID root

### ISSUE THREAD

**Issue by tristanplouz** [naegi/gateBluetooth#1]
Si l'id root dépasse un caractère il n'est pas reconnu comme id....
NUL

**Comment by philae-ael** [comment]
C'est à dire ? Quand un ID root est > 9 ?

**Comment by tristanplouz** [comment]
oui par exemple on a mis 221 il reconnait 2 comme id mais pas 221 comme id root
NUL.

**Comment by philae-ael** [comment]
As tu fais un reset de l'eeprom ou ajouté l'id 221 ? 

Le 15 août 2016 8:20 PM, à 8:20 PM, tristanplouz notifications@github.com a écrit:

**Comment by philae-ael** [comment]
![2016-08-16-202542_1366x768_scrot](https://cloud.githubusercontent.com/assets/1511446/17710937/d493890a-63ef-11e6-82a9-93036a15ef95.png)
D'après mes tests, ça marche.
